### ISSUE TITLE
Skype links don't open

### ISSUE THREAD

**Issue by steliyan** [meetfranz/recipe-skype#26]
I can't open a link using the **Skype** recipe. The issue happens with **Web links preview** with the option `on` or `off`. With the option `on` though the preview is properly displayed.

I am using the **Facebook Messenger** and everything works there.

**System:**
- `MacOS  Mojave 10.14.4 (18E226)`
- `Franz 5.0.1.1237`
- `Google Chrome 73.0.3683.103`*

\* I don't think the **Google Chrome** version is relevant because when I open the **DevTools** the issue is the URL is `null`.

I am attaching the log:
```
internal/url.js:239 Uncaught NodeError: Invalid URL: null
    at onParseError (internal/url.js:237:17)
    at parse (internal/url.js:246:3)
    at new URL (internal/url.js:321:5)
    at AppStore._openExternalUrl (/Applications/Franz.app/Contents/Resources/app.asar/stores/AppStore.js:277:23)
    at executeAction$$1 (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:579:19)
    at AppStore.res (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:571:16)
    at action.listeners.forEach.listener (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:24:70)
    at Array.forEach (<anonymous>)
    at Function.action.notify.params [as notify] (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:24:50)
    at Object.action [as openExternalUrl] (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:16:16)
NodeError @ internal/errors.js:159
onParseError @ internal/url.js:237
parse @ internal/url.js:246
URL @ internal/url.js:321
_openExternalUrl @ /Applications/Franz.app/Contents/Resources/app.asar/stores/AppStore.js:277
executeAction$$1 @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:579
res @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:571
action.listeners.forEach.listener @ /Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:24
action.notify.params @ /Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:24
action @ /Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:16
_handleIPCMessage @ /Applications/Franz.app/Contents/Resources/app.asar/stores/ServicesStore.js:462
executeAction$$1 @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:579
res @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:571
action.listeners.forEach.listener @ /Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:24
action.notify.params @ /Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:24
action @ /Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:16
webview.addEventListener.e @ /Applications/Franz.app/Contents/Resources/app.asar/models/Service.js:177
dispatchEvent @ /Applications/Franz.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:126
(anonymous) @ /Applications/Franz.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:82
emit @ events.js:182
```

I've restarted **Franz** a couple of times with no success.

_NOTE:_ I don't think it this should be merged with #18 as it reports an issue with the _beta_ version of **Franz.**

**Comment by libebcnof** [comment]
Samre Problem here, any updates???

**Comment by steliyan** [comment]
Fixed by https://github.com/meetfranz/recipe-skype/commit/7c67ec3dbcaadc370e0bf8c5140cd16f84771498.
Highly appriciated, @adlk!
